import 'package:flutter_test/flutter_test.dart';
import 'package:nero/features/docs/application/artifact_content_builder.dart';
import 'package:nero/features/docs/domain/doc_models.dart';

void main() {
  const builder = ArtifactContentBuilder();

  test('prepareDocumentContent returns validated markdown and parsed blocks', () async {
    final content = await builder.prepareDocumentContent(
      proposedTitle: 'Generate a doc about your capabilities',
      rawMarkdownContent: '# Nero Capabilities\n\n- Search\n- Generate files',
      activeRequestPrompt: 'Generate a doc about your capabilities',
      latestUserPrompt: null,
    );

    expect(content, isNotNull);
    expect(content!.title, 'Nero Capabilities');
    expect(content.markdownContent, '# Nero Capabilities\n\n- Search\n- Generate files');
    expect(content.blocks.first, isA<HeadingBlock>());
    expect(content.blocks.last, isA<BulletListBlock>());
  });

  test('prepareDocumentContent rejects planning prose', () async {
    final content = await builder.prepareDocumentContent(
      proposedTitle: 'Capabilities',
      rawMarkdownContent:
          'We need to call generate_docx with title and markdown_content.',
      activeRequestPrompt: 'Generate a document',
      latestUserPrompt: null,
    );

    expect(content, isNull);
  });

  test('prepared content builds a doc request without changing content', () async {
    final content = await builder.prepareDocumentContent(
      proposedTitle: 'Architecture Summary',
      rawMarkdownContent: '# Architecture Summary\n\nParagraph text.',
      activeRequestPrompt: 'Create a doc',
      latestUserPrompt: null,
    );

    final request = content!.toDocRequest(
      pageSettings: const PageSettings(paperSize: 'letter'),
      footerText: 'Generated by Nero',
    );

    expect(request.title, 'Architecture Summary');
    expect(request.footerText, 'Generated by Nero');
    expect(request.blocks.length, 2);
  });
}
