import '../../docs/application/artifact_content_builder.dart';
import '../../docs/domain/doc_models.dart';
import '../../tools/domain/tool_types.dart';
import '../domain/chat_message.dart';
import 'native_docx_tool_bridge.dart';
import 'native_output_tool_bridge.dart';
import 'sarvam_api_client.dart';
import 'web_tools.dart';

typedef ArtifactApplyCallback =
    void Function(GeneratedArtifactReference artifact);
typedef ArtifactActivityCallback = void Function(ChatActivity activity);
typedef ArtifactFailureCallback = void Function(Object error);

class DocumentArtifactToolExecutor {
  const DocumentArtifactToolExecutor({
    ArtifactContentBuilder? contentBuilder,
    required NativeDocxToolBridge nativeDocxToolBridge,
    required NativeOutputToolBridge nativeOutputToolBridge,
  }) : _contentBuilder = contentBuilder ?? const ArtifactContentBuilder(),
       _nativeDocxToolBridge = nativeDocxToolBridge,
       _nativeOutputToolBridge = nativeOutputToolBridge;

  final ArtifactContentBuilder _contentBuilder;
  final NativeDocxToolBridge _nativeDocxToolBridge;
  final NativeOutputToolBridge _nativeOutputToolBridge;

  Future<ToolExecutionResult> execute({
    required SarvamToolCall toolCall,
    required String conversationId,
    required String? messageId,
    required String? activeRequestPrompt,
    required String? latestUserPrompt,
    required ArtifactApplyCallback onArtifact,
    required ArtifactActivityCallback onActivity,
    ArtifactFailureCallback? onDocxFailure,
  }) async {
    final preparedContent = await _contentBuilder.prepareDocumentContent(
      proposedTitle: _coerceToolString(toolCall.arguments['title']),
      rawMarkdownContent: _coerceToolString(
        toolCall.arguments['markdown_content'],
      ),
      activeRequestPrompt: activeRequestPrompt,
      latestUserPrompt: latestUserPrompt,
    );
    if (preparedContent == null) {
      return ToolExecutionResult(
        success: false,
        summary:
            toolCall.name == 'generate_docx'
                ? 'DOCX generation failed.'
                : 'PDF generation failed.',
        formattedOutput:
            toolCall.name == 'generate_docx'
                ? 'The generate_docx tool requires valid document markdown_content.'
                : 'The generate_report_pdf tool requires valid document markdown_content.',
      );
    }

    return switch (toolCall.name) {
      'generate_docx' => _nativeDocxToolBridge.execute(
        title: preparedContent.title,
        blocks: preparedContent.blocks,
        conversationId: conversationId,
        messageId: messageId ?? 'standalone_docx',
        onArtifact: onArtifact,
        onActivity: onActivity,
        onFailure: onDocxFailure,
      ),
      'generate_report_pdf' => _nativeOutputToolBridge.execute(
        toolType: ToolType.generateReportPdf,
        title: preparedContent.title,
        parameters: <String, dynamic>{
          'title': preparedContent.title,
          'request': preparedContent
              .toDocRequest(
                pageSettings: PageSettings(
                  paperSize: _coerceToolString(toolCall.arguments['paper_size'])
                          .isEmpty
                      ? 'letter'
                      : _coerceToolString(toolCall.arguments['paper_size']),
                  orientation: _coerceToolString(
                        toolCall.arguments['orientation'],
                      ).isEmpty
                      ? 'portrait'
                      : _coerceToolString(toolCall.arguments['orientation']),
                ),
                footerText: 'Generated by Nero',
              )
              .toJson(),
          'content': preparedContent.markdownContent,
        },
        conversationId: conversationId,
        messageId: messageId,
        successSummary: 'Created PDF document',
        failurePrefix: 'PDF generation failed',
        activityTitle: 'Created file',
        onArtifact: onArtifact,
        onActivity: onActivity,
      ),
      _ => ToolExecutionResult(
        success: false,
        summary: 'Unsupported document artifact tool ${toolCall.name}.',
        formattedOutput:
            'Tool ${toolCall.name} is not supported by the document artifact executor.',
      ),
    };
  }

  String _coerceToolString(Object? value) {
    return value?.toString().trim() ?? '';
  }
}
