import '../../docs/application/artifact_result_adapter.dart';
import '../../docs/application/doc_generation_service.dart';
import '../../docs/domain/doc_models.dart';
import '../domain/chat_message.dart';
import 'web_tools.dart';

typedef DocxArtifactApplyCallback =
    void Function(GeneratedArtifactReference artifact);
typedef DocxActivityRecordCallback = void Function(ChatActivity activity);
typedef DocxFailureReportCallback = void Function(Object error);

class NativeDocxToolBridge {
  const NativeDocxToolBridge({
    required DocGenerationService docGenerationService,
    ArtifactResultAdapter? artifactResultAdapter,
  }) : _docGenerationService = docGenerationService,
       _artifactResultAdapter = artifactResultAdapter ?? const ArtifactResultAdapter();

  final DocGenerationService _docGenerationService;
  final ArtifactResultAdapter _artifactResultAdapter;

  Future<ToolExecutionResult> execute({
    required String title,
    required List<DocBlock> blocks,
    required String conversationId,
    required String? messageId,
    String successSummary = 'Created DOCX document',
    String activityTitle = 'Created document',
    String artifactLabel = 'generated DOCX artifact',
    DocxArtifactApplyCallback? onArtifact,
    DocxActivityRecordCallback? onActivity,
    DocxFailureReportCallback? onFailure,
  }) async {
    try {
      final workspaceItem = await _docGenerationService.generateDocx(
        request: DocRequest(
          title: title,
          blocks: blocks,
          pageSettings: const PageSettings(paperSize: 'letter'),
          footerText: 'Generated by Nero',
        ),
        conversationId: conversationId,
        messageId: messageId,
      );
      final outcome = _artifactResultAdapter.outcomeForWorkspaceItem(
        item: workspaceItem,
        successSummary: successSummary,
        activityTitle: activityTitle,
        artifactLabel: artifactLabel,
      );
      for (final artifact in outcome.artifacts) {
        onArtifact?.call(artifact);
      }
      final activity = outcome.activity;
      if (activity != null) {
        onActivity?.call(activity);
      }
      return outcome.toolResult;
    } catch (error) {
      onFailure?.call(error);
      return ToolExecutionResult(
        success: false,
        summary: 'DOCX generation failed.',
        formattedOutput:
            'Document generation failed in the native Apache POI pipeline: $error',
      );
    }
  }
}
