import '../../chat/domain/chat_message.dart';
import '../../tools/application/local_tool_runtime_service.dart';
import '../../tools/domain/tool_runtime_models.dart' as runtime;
import '../../tools/domain/tool_types.dart';
import '../../../platform/device/native_bridge_service.dart';
import '../domain/doc_models.dart';
import 'artifact_result_adapter.dart';
import 'doc_generation_service.dart';

class InlineArtifactGenerator {
  InlineArtifactGenerator({
    DocGenerationService? docGenerationService,
    LocalToolRuntimeService? localToolRuntimeService,
    NativeBridgeService? nativeBridgeService,
    ArtifactResultAdapter? artifactResultAdapter,
  }) : _docGenerationService = docGenerationService ?? DocGenerationService(),
       _localToolRuntimeService =
           localToolRuntimeService ??
           LocalToolRuntimeService(
             nativeBridgeService: nativeBridgeService ?? NativeBridgeService(),
           ),
       _artifactResultAdapter = artifactResultAdapter ?? const ArtifactResultAdapter();

  final DocGenerationService _docGenerationService;
  final LocalToolRuntimeService _localToolRuntimeService;
  final ArtifactResultAdapter _artifactResultAdapter;

  Future<GeneratedArtifactReference?> generateDocxArtifact({
    required String conversationId,
    required String messageId,
    required String title,
    required String markdownContent,
    required List<DocBlock> blocks,
  }) async {
    final normalizedTitle = title.trim().isEmpty ? 'Nero Document' : title.trim();
    final normalizedMarkdown = markdownContent.trim();
    if (normalizedMarkdown.isEmpty) {
      return null;
    }

    final workspaceItem = await _docGenerationService.generateDocx(
      request: DocRequest(
        title: normalizedTitle,
        blocks: blocks,
        pageSettings: const PageSettings(paperSize: 'letter'),
        footerText: 'Generated by Nero',
      ),
      conversationId: conversationId,
      messageId: messageId,
    );
    return _artifactResultAdapter.referenceForWorkspaceItem(workspaceItem);
  }

  Future<GeneratedArtifactReference?> generatePdfArtifact({
    required String conversationId,
    required String messageId,
    required String title,
    required String markdownContent,
    required List<DocBlock> blocks,
  }) async {
    final normalizedTitle = title.trim().isEmpty ? 'Nero PDF' : title.trim();
    final normalizedMarkdown = markdownContent.trim();
    if (normalizedMarkdown.isEmpty) {
      return null;
    }

    final docRequest = DocRequest(
      title: normalizedTitle,
      blocks: blocks,
      pageSettings: const PageSettings(paperSize: 'letter'),
      footerText: 'Generated by Nero',
    );
    final request = runtime.ToolExecutionRequest(
      jobId: 'generate_report_pdf_${DateTime.now().microsecondsSinceEpoch}',
      toolType: ToolType.generateReportPdf,
      parameters: <String, dynamic>{
        'title': normalizedTitle,
        'request': docRequest.toJson(),
        'content': normalizedMarkdown,
      },
      conversationId: conversationId,
      messageId: messageId,
    );
    final runtimeResult = await _localToolRuntimeService.executeToolRequest(
      request: request,
    );
    if (runtimeResult.status != runtime.RuntimeJobStatus.completed ||
        runtimeResult.artifacts.isEmpty) {
      return null;
    }
    return _artifactResultAdapter.referenceForDescriptor(
      runtimeResult.artifacts.first,
    );
  }
}
